package:
  name: cavpp_audio_convert
  version: 0.1.11a0

source:
  git_tag: 0.1.11a0					[py27]
  git_url: https://github.com/cavpp/audio_convert.git 	[py27]

build:
  number: 3
  string: c
  entry_points:
    -  makemp3 = audio_convert.scripts.audioConvert:installed_start

requirements:
  build:
    - python
    - setuptools
    - onesheet >=0.1.4

  run:
    - python <3.0
    - onesheet >=0.1.4

test:
  imports:
    - audio_convert

  commands:
    - makemp3 -h
    - lame --license
    - ffprobe -L

about:
  home: https://github.com/cavpp/audio_convert
  license: GLP
  summary: "Converts wav files into MP3 files according to CAVPP standards.."

app:
  entry: makemp3 -g
  summary: Renames and converts images into CAVPP/CAPS naming and specs.
